# 16x16 Minecraft-style item icons, saved 4x (64x64) with nearest-neighbour scaling.
# Regenerate with: python3 scripts/draw-item-textures.py  (needs Pillow)
from PIL import Image
import sys, os
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..', 'client', 'public', 'textures')
P = {
  '.': None,
  'k': (40, 28, 16),     # dark outline brown
  'h': (78, 54, 28),    # handle mid
  'H': (118, 84, 44),   # handle light
  'w': (150, 115, 65),    # wood head dark
  'W': (190, 152, 96),   # wood head
  'L': (225, 190, 130),   # wood head light
  'o': (30, 30, 30),     # black outline
  'r': (190, 30, 30), 'R': (230, 70, 60), 'g': (70, 120, 30), 'G': (110, 170, 50),
  's': (90, 90, 90), 'S': (125, 125, 125), 'T': (160, 160, 160), 'D': (60, 60, 60),
  'f': (255, 170, 40), 'F': (255, 220, 90),
  'p': (150, 110, 60), 'P': (185, 140, 80), 'q': (120, 88, 48),
  'i': (200, 200, 200),
}
ART = {
'stick': """
................
................
..............k.
.............kHk
............kHhk
...........kHhk.
..........kHhk..
.........kHhk...
........kHhk....
.......kHhk.....
......kHhk......
.....kHhk.......
....kHhk........
....khk.........
.....k..........
................""",
'pickaxe': """
................
....kkkkkkk.....
...kLWWWWWWkk...
...kkkkkkWLWWk..
.........kWWWk..
........kHkWWk..
.......kHhkkWk..
......kHhk.kWk..
.....kHhk...kk..
....kHhk........
...kHhk.........
..kHhk..........
.kHhk...........
.khk............
..k.............
................""",
'axe': """
................
............kk..
..kkkk.....kHk..
..kLWWk...kHhk..
..kLWWWk.kHhk...
..kLWWWWkHhk....
..kLWWWkHhk.....
..kLWWkHhk......
..kLWkHhk.......
...kkHhk........
...kHhk.........
..kHhk..........
.kHhk...........
.khk............
..k.............
................""",
'shovel': """
................
..........kkkk..
.........kLLLWk.
........kLLWWWk.
........kLWWWWk.
........kWWWWwk.
.........kWWwk..
........kHkkk...
.......kHhk.....
......kHhk......
.....kHhk.......
....kHhk........
...kHhk.........
..kHhk..........
..khk...........
...k............""",
'sword': """
................
.............kk.
............kLk.
...........kLWk.
..........kLWk..
.........kLWk...
........kLWk....
...kk..kLWk.....
...kWkkLWk......
....kWLWk.......
.....kHk........
....kHkWk.......
...kHk.kWk......
..kHk...kk......
..kk............
................""",
'apple': """
................
.......k........
.......kgg......
......kGgg......
....oooko.oo....
...oRRRroRRRo...
..oRiRRRRRRRro..
..oRiRRRRRRRro..
..oRRRRRRRRrro..
..oRRRRRRRRrro..
..oRRRRRRRrrro..
...oRRRRRrrro...
...orRRrrrrro...
....orrroorro...
.....ooo..oo....
................""",
}
# Block faces (full 16x16, no transparency)
BLOCKS = {
'crafting_table': """
kkkkkkkkkkkkkkkk
kLPLPkLPLPkLPLPk
kPsPPkPPsPkPPTPk
kLPTPkLTPPkLPPPk
kkkkkkkkkkkkkkkk
kPPPPPPPPPPPPPPk
kpPPpPPPpPPPpPPk
kPPPPkkkkkkPPPPk
kpPPPkqqqqkPPpPk
kPPPPkqqqqkPPPPk
kPPpPkqqqqkPpPPk
kPPPPkkkkkkPPPPk
kpPPPPPpPPPPPPpk
kPPPPpPPPPPpPPPk
kPpPPPPPPpPPPPPk
kkkkkkkkkkkkkkkk""",
'furnace': """
DDDDDDDDDDDDDDDD
DSTSSTSSSTSSTSSD
DSSSSSSSSSSSSSSD
DTSSDDDDDDDDSSTD
DSSDsssssssssDSD
DSSDsDDDDDDDsDSD
DSTDsDooooDDsDSD
DSSDsDoFfoDDsDTD
DSSDsDofFfoDsDSD
DSSDsDoffFfDsDSD
DSTDsDDDDDDDsDSD
DSSDsssssssssDSD
DSSSDDDDDDDDDSSD
DTSSSSTSSSSSTSSD
DSSTSSSSSTSSSSSD
DDDDDDDDDDDDDDDD""",
'chest': """
kkkkkkkkkkkkkkkk
kLLLLLLLLLLLLLLk
kPPPPPPPPPPPPPPk
kPpPPPPPPPPPpPPk
kPPPPPPPPPPPPPPk
kkkkkkkkkkkkkkkk
kPPPPPPiiPPPPPPk
kpPPPPPiDPPPPPpk
kPPPPPPiiPPPPPPk
kPPPPPPPPPPPPPPk
kPPpPPPPPPPPPPPk
kPPPPPPPPPPpPPPk
kPPPPPPPPPPPPPPk
kpPPPPPPPPPPPPpk
kPPPPPPPPPPPPPPk
kkkkkkkkkkkkkkkk""",
}
def render(name, art, opaque):
    rows = [r for r in art.strip('\n').split('\n')]
    assert len(rows) == 16 and all(len(r) == 16 for r in rows), (name, [len(r) for r in rows], len(rows))
    im = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            c = P[ch]
            if c: im.putpixel((x, y), c + (255,))
            elif opaque: raise SystemExit(f'{name}: transparent pixel in block face at {x},{y}')
    im.resize((64, 64), Image.NEAREST).save(os.path.join(OUT, name + '.png'), optimize=True)
for n, a in ART.items(): render(n, a, False)
for n, a in BLOCKS.items(): render(n, a, True)
print('ok', len(ART) + len(BLOCKS))
